#!/bin/bash

FILES="src/main.c src/SSD1306.c src/Inputs.c src/Voices.c"
OUTPUT="build/fSharp32.elf"
MCU="atmega1284"
FLAGS="-O3 -Wfatal-errors"

readAndExit () {
    read
    exit 1
}

if [ ! -d "build" ]; then
    mkdir "build"
fi

avr-gcc -mmcu=$MCU $FLAGS -o $OUTPUT $FILES || readAndExit
avr-size -C --mcu=atmega1284 $OUTPUT

read

sudo avrdude -p m1284 -c pickit2 -B 400kHz -U flash:w:build/fSharp32.elf:a

read
