#!/bin/bash

FILES="src/main.c src/SSD1306.c src/Modulator.c"
OUTPUT="build/fSharp32.elf"

readAndExit () {
    read
    exit 1
}

if [ ! -d "build" ]; then
    mkdir "build"
fi

avr-gcc -mmcu=atmega1284 -O2 -Wfatal-errors -o $OUTPUT $FILES || readAndExit
avr-size -C --mcu=atmega1284 $OUTPUT
read
